### PR TITLE
Test bzfile_ value before reading/writing/closing

### PR DESCRIPTION
**Pull request by jwon02**

### CODE REVIEW

**Comment by jwon02** [comment]
Ping for review.

**Comment by jasonimercer** [comment]
Looks good to me. Style doesn't match ROS but it matches the file. The exception string seems awkward. Would you consider the minor change:

"cannot XYX unopened bzfile"

**Comment by mikepurvis** [comment]
As in #13, if you want this in our testing, please open a PR to the _upstream_ lunar-devel branch.

**Comment by jwon02** [comment]
Let me open a PR to the upstream branch with revised exception messages.

**Pull request closed without merging**
