### PR TITLE
Sync kinetic devel with upstream

### PR DESCRIPTION
**Pull request by jliviero**
Our fork being behind was making upstream PRs awkward.  Since we're now [pointing back at upstream](http://gitlab/sweng-infra/rosdistro_internal/blob/master/indigo/distribution.yaml#L2608), I see no reason not to bring our fork up to speed.

FYI @mikepurvis, and not sure who else would be a relevant party?

### CODE REVIEW

**Comment by mikepurvis** [comment]
Do we have anything actually in this fork other than merge commits? I'd say just hard reset to upstream and force push.

**Comment by jliviero** [comment]
Doesn't seem like it, and even if we do, we should probably make sure this matches upstream exactly.

Option 3 would be to nuke the entire fork and recreate it from upstream, so that all our branches are synced in one go.

**Comment by mikepurvis** [comment]
We don't need all branches, though, just kinetic-devel, right?

**Comment by jliviero** [comment]
Seems like that's the case, though you'd know better than I.

If anyone here wants to do dev on ros_comm (like backporting to indigo), having all branches synced makes life easier for them.  It's simply to fork the upstream to an individual dev account if need be though, so I'm not really concerned one way or the other.

**Comment by mikepurvis** [comment]
Have force pushed upstream's kinetic devel to ours, which Github has interpreted as "merging" this, ha.

**Pull request merged**
